/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorksInternshipsSaharianoRouteImport } from './routes/works-internships/sahariano'
import { Route as WorksInternshipsMetamaRouteImport } from './routes/works-internships/metama'
import { Route as WorksInternshipsDigiluxRouteImport } from './routes/works-internships/digilux'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as EducationBtsDsiRouteImport } from './routes/education/bts-dsi'
import { Route as EducationBachelorSirRouteImport } from './routes/education/bachelor-sir'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksInternshipsSaharianoRoute =
  WorksInternshipsSaharianoRouteImport.update({
    id: '/works-internships/sahariano',
    path: '/works-internships/sahariano',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorksInternshipsMetamaRoute = WorksInternshipsMetamaRouteImport.update({
  id: '/works-internships/metama',
  path: '/works-internships/metama',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksInternshipsDigiluxRoute = WorksInternshipsDigiluxRouteImport.update({
  id: '/works-internships/digilux',
  path: '/works-internships/digilux',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationBtsDsiRoute = EducationBtsDsiRouteImport.update({
  id: '/education/bts-dsi',
  path: '/education/bts-dsi',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationBachelorSirRoute = EducationBachelorSirRouteImport.update({
  id: '/education/bachelor-sir',
  path: '/education/bachelor-sir',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/education/bachelor-sir': typeof EducationBachelorSirRoute
  '/education/bts-dsi': typeof EducationBtsDsiRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/works-internships/digilux': typeof WorksInternshipsDigiluxRoute
  '/works-internships/metama': typeof WorksInternshipsMetamaRoute
  '/works-internships/sahariano': typeof WorksInternshipsSaharianoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/education/bachelor-sir': typeof EducationBachelorSirRoute
  '/education/bts-dsi': typeof EducationBtsDsiRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/works-internships/digilux': typeof WorksInternshipsDigiluxRoute
  '/works-internships/metama': typeof WorksInternshipsMetamaRoute
  '/works-internships/sahariano': typeof WorksInternshipsSaharianoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/education/bachelor-sir': typeof EducationBachelorSirRoute
  '/education/bts-dsi': typeof EducationBtsDsiRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/works-internships/digilux': typeof WorksInternshipsDigiluxRoute
  '/works-internships/metama': typeof WorksInternshipsMetamaRoute
  '/works-internships/sahariano': typeof WorksInternshipsSaharianoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/education/bachelor-sir'
    | '/education/bts-dsi'
    | '/projects/$projectId'
    | '/works-internships/digilux'
    | '/works-internships/metama'
    | '/works-internships/sahariano'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/education/bachelor-sir'
    | '/education/bts-dsi'
    | '/projects/$projectId'
    | '/works-internships/digilux'
    | '/works-internships/metama'
    | '/works-internships/sahariano'
  id:
    | '__root__'
    | '/'
    | '/education/bachelor-sir'
    | '/education/bts-dsi'
    | '/projects/$projectId'
    | '/works-internships/digilux'
    | '/works-internships/metama'
    | '/works-internships/sahariano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducationBachelorSirRoute: typeof EducationBachelorSirRoute
  EducationBtsDsiRoute: typeof EducationBtsDsiRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  WorksInternshipsDigiluxRoute: typeof WorksInternshipsDigiluxRoute
  WorksInternshipsMetamaRoute: typeof WorksInternshipsMetamaRoute
  WorksInternshipsSaharianoRoute: typeof WorksInternshipsSaharianoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works-internships/sahariano': {
      id: '/works-internships/sahariano'
      path: '/works-internships/sahariano'
      fullPath: '/works-internships/sahariano'
      preLoaderRoute: typeof WorksInternshipsSaharianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works-internships/metama': {
      id: '/works-internships/metama'
      path: '/works-internships/metama'
      fullPath: '/works-internships/metama'
      preLoaderRoute: typeof WorksInternshipsMetamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works-internships/digilux': {
      id: '/works-internships/digilux'
      path: '/works-internships/digilux'
      fullPath: '/works-internships/digilux'
      preLoaderRoute: typeof WorksInternshipsDigiluxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/bts-dsi': {
      id: '/education/bts-dsi'
      path: '/education/bts-dsi'
      fullPath: '/education/bts-dsi'
      preLoaderRoute: typeof EducationBtsDsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education/bachelor-sir': {
      id: '/education/bachelor-sir'
      path: '/education/bachelor-sir'
      fullPath: '/education/bachelor-sir'
      preLoaderRoute: typeof EducationBachelorSirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducationBachelorSirRoute: EducationBachelorSirRoute,
  EducationBtsDsiRoute: EducationBtsDsiRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  WorksInternshipsDigiluxRoute: WorksInternshipsDigiluxRoute,
  WorksInternshipsMetamaRoute: WorksInternshipsMetamaRoute,
  WorksInternshipsSaharianoRoute: WorksInternshipsSaharianoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
